\documentclass{article}

\begin{document}

\title{Desire for Extended Lifespan is Conditional}

\author{Joe, Kristen, Yoni}

\maketitle

<<echo=FALSE>>=
library(ggplot2)
library(reshape)

survey <- read.csv("data/surveyResults.csv",header=TRUE)
@

\section{Results}

\begin{figure}{h}
<<fig=TRUE, echo=FALSE>>=
df <- melt(survey, measure.vars = c(20,21,22))
df$variable <- factor(df$variable, labels = c("Q2","Q3","Q4"))
df$variable <- factor(df$variable, c("Q3", "Q4", "Q2"))
df <- cast(df, variable + value ~ ., length)
df$all <- df[,"(all)"]
df$value <- factor(df$value, c("85","120","150","Unlimited"))
print(ggplot(df, aes(x = value, weight = all, fill = variable)) + geom_bar(position = "dodge"))
@
\caption{If either mental or physical decline is expected, more than
half want to die at 85. But, if neither mental nor physical decline is
expected, then 80\% want to live $\geq$ 120 years!}
\end{figure}

The responses for ``120'' and ``150'' do not change signiﬁcantly
between the Both case and the Physically-only or Mentally-only
cases. Therefore the ratio of ``unlimited'' to ``85'' is used as the
dependent variable for the following charts (and denoted ``unlimited:85'').

\end{document}
