\documentclass{article}

\begin{document}

\title{Desire for Extended Lifespan is Conditional}

\author{Joe, Kristen, Yoni}

\maketitle

<<echo=FALSE>>=
library(ggplot2)
library(reshape)

survey <- read.csv("data/surveyResults.csv",header=TRUE)
@

\section{Results}

\begin{figure}
<<fig=TRUE, echo=FALSE>>=
df <- melt(survey, measure.vars = c(20,21,22))
df$variable <- factor(df$variable, labels = c("Q2","Q3","Q4"))
df$variable <- factor(df$variable, c("Q3", "Q4", "Q2"))
df2 <- cast(df, variable + value ~ ., length)
df2$all <- df2[,"(all)"]
df2$value <- factor(df2$value, c("85","120","150","Unlimited"))
print(ggplot(df2, aes(x = value, weight = all, fill = variable)) + geom_bar(position = "dodge"))
@
\caption{If either mental or physical decline is expected, more than
half want to die at 85. But, if neither mental nor physical decline is
expected, then 80\% want to live $\geq$ 120 years!}
\end{figure}

The responses for ``120'' and ``150'' do not change signiﬁcantly
between the Both case and the Physically-only or Mentally-only
cases. Therefore the ratio of ``unlimited'' to ``85'' is used as the
dependent variable for the following charts (and denoted ``unlimited:85'').

<<echo=FALSE>>=
df$Health.Status <- df$Q6.How.healthy.do.you.feel..physically.and.mentally.
df$Health.Status <- factor(df$Health.Status, c("Severely unhealthy", "Unhealthy", "Fine", "Quite healthy", "Perfectly healthy"))
df2 <- cast(df, variable + value + Age.Range + Health.Status ~ ., length)
@

\begin{figure}
<<fig=TRUE, echo=FALSE>>=
df3 <- ddply(df2, c("Age.Range", "variable"), function(x) sum(x[x$value=="Unlimited","(all)"]/sum(x[x$value=="85","(all)"])))
print(ggplot(df3, aes(x = Age.Range, group=variable, y=V1)) + geom_line(aes(colour = variable)) + geom_point(aes(colour = variable)) + xlab("Age") + ylab("Unlimied:85 ratio"))
@
\caption{The unlimited:85 ratio as a function of age group.}
\end{figure}

\begin{figure}
<<fig=TRUE, echo=FALSE>>=
df3 <- ddply(df2, c("Health.Status", "variable"), function(x) sum(x[x$value=="Unlimited","(all)"]/sum(x[x$value=="85","(all)"])))
print(ggplot(df3, aes(x = Health.Status, group=variable, y=V1)) + geom_line(aes(colour = variable)) + geom_point(aes(colour = variable)) + xlab("Age") + ylab("Unlimied:85 ratio"))
@
\caption{The unlimited:85 ratio as a function of health status.}
\end{figure}

\end{document}
