\documentclass{article}

\begin{document}

\title{Desire for Extended Lifespan is Conditional}

\author{Yoni Donner, Kristen Fortney}

\maketitle

<<echo=FALSE>>=
library(ggplot2)
library(reshape)

survey <- read.csv("data/surveyResults.csv",header=TRUE)
@

\section{Results}

\begin{figure}
<<fig=TRUE, echo=FALSE>>=
df <- melt(survey, measure.vars = c(20,21,22))
df$variable <- factor(df$variable, labels = c("Q2","Q3","Q4"))
df$variable <- factor(df$variable, c("Q3", "Q4", "Q2"))
df2 <- cast(df, variable + value ~ ., length)
df2$all <- df2[,"(all)"]
df2$value <- factor(df2$value, c("85","120","150","Unlimited"))
print(ggplot(df2, aes(x = value, weight = all, fill = variable)) + geom_bar(position = "dodge") + xlab("Desired age") + ylab("Number of respondents") + scale_fill_discrete(name="Question", breaks=c("Q3","Q2","Q4"), labels=c("Physically but not mentally", "Mentally but not physically", "Both")))
@
\caption{If either mental or physical decline is expected, more than
half want to die at 85. But, if neither mental nor physical decline is
expected, then 80\% want to live $\geq$ 120 years!}
\end{figure}

The responses for ``120'' and ``150'' do not change signiﬁcantly
between the Both case and the Physically-only or Mentally-only
cases. Therefore the ratio of ``unlimited'' to ``85'' is used as the
dependent variable for the following charts (and denoted ``unlimited:85'').

<<echo=FALSE>>=
df$Health.Status <- df$Q6.How.healthy.do.you.feel..physically.and.mentally.
df$Health.Status <- factor(df$Health.Status, c("Severely unhealthy", "Unhealthy", "Fine", "Quite healthy", "Perfectly healthy"))
df$Self.Esteem <- df$Q10.I.have.high.self.esteem.
df$Self.Esteem <- factor(df$Self.Esteem, c("Not at all true of me", "Not very true of me", "Very true of me", "Completely true of me"))
df$Science.Interest <- df$Q7.How.interested.are.you.in.topics.related.to.science.and.technology.
df$Science.Interest <- factor(df$Science.Interest, c("Disinterested", "Slightly interested", "Moderately interested", "Quite interested", "Avidly interested"))
df2 <- cast(df, variable + value + Age.Range + Health.Status +
Self.Esteem + Science.Interest ~ ., length)
@

\begin{figure}
<<fig=TRUE, echo=FALSE>>=
df3 <- ddply(df2, c("Age.Range", "variable"), function(x) sum(x[x$value=="Unlimited","(all)"]/sum(x[x$value=="85","(all)"])))
print(ggplot(df3, aes(x = Age.Range, group=variable, y=V1)) + geom_line(aes(colour = variable)) + geom_point(aes(colour = variable)) + xlab("Age") + ylab("Unlimied:85 ratio"))
@
\caption{The unlimited:85 ratio as a function of age group.}
\end{figure}

\begin{figure}
<<fig=TRUE, echo=FALSE>>=
df3 <- ddply(df2, c("Self.Esteem", "variable"), function(x) sum(x[x$value=="Unlimited","(all)"]/sum(x[x$value=="85","(all)"])))
print(ggplot(df3, aes(x = Self.Esteem, group=variable, y=V1)) + geom_line(aes(colour = variable)) + geom_point(aes(colour = variable)) + xlab("Self esteem") + ylab("Unlimied:85 ratio"))
@
\caption{The unlimited:85 ratio as a function of self esteem.}
\end{figure}

\begin{figure}
<<fig=TRUE, echo=FALSE>>=
df3 <- ddply(df2, c("Science.Interest", "variable"), function(x) sum(x[x$value=="Unlimited","(all)"]/sum(x[x$value=="85","(all)"])))
print(ggplot(df3, aes(x = Science.Interest, group=variable, y=V1)) + geom_line(aes(colour = variable)) + geom_point(aes(colour = variable)) + xlab("Interest in science") + ylab("Unlimied:85 ratio"))
@
\caption{The unlimited:85 ratio as a function of interest in science.}
\end{figure}

\begin{figure}
<<fig=TRUE, echo=FALSE>>=
df3 <- ddply(df2, c("Health.Status", "variable"), function(x) sum(x[x$value=="Unlimited","(all)"]/sum(x[x$value=="85","(all)"])))
print(ggplot(df3, aes(x = Health.Status, group=variable, y=V1)) + geom_line(aes(colour = variable)) + geom_point(aes(colour = variable)) + xlab("Health status") + ylab("Unlimied:85 ratio"))
@
\caption{The unlimited:85 ratio as a function of health status.}
\end{figure}

\end{document}
